don't let formatter change code
this avoids conflicts due to code formatting. You have to run the
formatter manually

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -12,8 +12,6 @@ jobs:
       - name: Install JuliaFormatter
         # Using a one-liner to avoid adding it to Project.toml if you prefer
         run: julia -e 'using Pkg; Pkg.add("JuliaFormatter")'
-      - uses: julia-actions/julia-format@v4
-        with:
-        # this lets GitHub automatically fix the formatting and commit it back to the branch
-          annotate: true
-
+      - name: Check Formatting
+        # This will return a non-zero exit code (failing the CI) if code is messy
+        run: julia -e 'using JuliaFormatter; format(".", verbose=true) || exit(1)'
